// react-form/src/App.jsx
import { useEffect, useState } from "react";
import "./App.css";

function App() {
  const initialState = {
    dni: "",
    nombres: "",
    apellidos: "",
    fechaNacimiento: "",
    genero: "",
    ciudad: ""
  };

  const [formData, setFormData] = useState(initialState);
  const [errors, setErrors] = useState({});
  const [forms, setForms] = useState([]);
  const [isEditing, setIsEditing] = useState(false);
  const [editId, setEditId] = useState(null);

  // Obtener todos los registros
  const getForms = async () => {
    try {
      const res = await fetch("http://localhost:5000/api/forms");
      if (!res.ok) throw new Error("Error al obtener registros");
      const data = await res.json();
      setForms(data);
    } catch (err) {
      console.error("getForms:", err);
    }
  };

  useEffect(() => {
    getForms();
  }, []);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const validate = () => {
    const newErrors = {};
    if (!formData.dni) newErrors.dni = "DNI es obligatorio";
    if (!formData.nombres) newErrors.nombres = "Nombres son obligatorios";
    if (!formData.apellidos) newErrors.apellidos = "Apellidos son obligatorios";
    if (!formData.fechaNacimiento) newErrors.fechaNacimiento = "Fecha de nacimiento es obligatoria";
    if (!formData.genero) newErrors.genero = "Seleccione un género";
    if (!formData.ciudad) newErrors.ciudad = "Seleccione una ciudad";
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Crear o actualizar
  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!validate()) return;

    try {
      if (isEditing && editId) {
        // UPDATE
        const res = await fetch(`http://localhost:5000/api/form/${editId}`, {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(formData)
        });
        if (!res.ok) throw new Error("Error al actualizar");
        // opcional: const updated = await res.json();
        setIsEditing(false);
        setEditId(null);
        setFormData(initialState);
      } else {
        // CREATE
        const res = await fetch("http://localhost:5000/api/form", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(formData)
        });
        if (!res.ok) throw new Error("Error al crear");
        setFormData(initialState);
      }
      await getForms();
      setErrors({});
      alert(isEditing ? "Registro actualizado" : "Formulario guardado correctamente");
    } catch (err) {
      console.error("handleSubmit:", err);
      alert("Hubo un error al guardar. Revisa la consola.");
    }
  };

  // Preparar formulario para editar
  const editForm = (form) => {
    setIsEditing(true);
    setEditId(form._id);
    setFormData({
      dni: form.dni || "",
      nombres: form.nombres || "",
      apellidos: form.apellidos || "",
      fechaNacimiento: form.fechaNacimiento || "",
      genero: form.genero || "",
      ciudad: form.ciudad || ""
    });
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const cancelEdit = () => {
    setIsEditing(false);
    setEditId(null);
    setFormData(initialState);
    setErrors({});
  };

  // Eliminar registro
  const deleteForm = async (id) => {
    if (!confirm("¿Eliminar este registro?")) return;
    try {
      const res = await fetch(`http://localhost:5000/api/form/${id}`, { method: "DELETE" });
      if (!res.ok) throw new Error("Error al eliminar");
      await getForms();
    } catch (err) {
      console.error("deleteForm:", err);
      alert("No se pudo eliminar el registro.");
    }
  };

  return (
    <div className="App">
      <h1>Formulario React</h1>

      <form onSubmit={handleSubmit}>
        <input
          type="text"
          name="dni"
          placeholder="DNI"
          value={formData.dni}
          onChange={handleChange}
        />
        {errors.dni && <p className="error">{errors.dni}</p>}

        <input
          type="text"
          name="nombres"
          placeholder="Nombres"
          value={formData.nombres}
          onChange={handleChange}
        />
        {errors.nombres && <p className="error">{errors.nombres}</p>}

        <input
          type="text"
          name="apellidos"
          placeholder="Apellidos"
          value={formData.apellidos}
          onChange={handleChange}
        />
        {errors.apellidos && <p className="error">{errors.apellidos}</p>}

        <input
          type="date"
          name="fechaNacimiento"
          value={formData.fechaNacimiento}
          onChange={handleChange}
        />
        {errors.fechaNacimiento && <p className="error">{errors.fechaNacimiento}</p>}

        <div className="form-group">
          <label className="label-center">Género:</label>
          <div className="radio-group-horizontal">
            <label>
              <input
                type="radio"
                name="genero"
                value="M"
                checked={formData.genero === "M"}
                onChange={handleChange}
              /> Masculino
            </label>
            <label>
              <input
                type="radio"
                name="genero"
                value="F"
                checked={formData.genero === "F"}
                onChange={handleChange}
              /> Femenino
            </label>
          </div>
          {errors.genero && <p className="error">{errors.genero}</p>}
        </div>

        <select name="ciudad" value={formData.ciudad} onChange={handleChange}>
          <option value="">Seleccione ciudad</option>
          <option value="Quito">Quito</option>
          <option value="Guayaquil">Guayaquil</option>
          <option value="Milagro">Milagro</option>
        </select>
        {errors.ciudad && <p className="error">{errors.ciudad}</p>}

        <button type="submit">{isEditing ? "Actualizar" : "Guardar"}</button>
        {isEditing && (
          <button type="button" style={{ marginTop: "8px" }} onClick={cancelEdit}>
            Cancelar
          </button>
        )}
      </form>

      {/* Lista de registros (tabla simple) */}
      <h2 style={{ marginTop: 30 }}>Registros</h2>
      <div style={{ overflowX: "auto" }}>
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr>
              <th style={{ border: "1px solid #ccc", padding: 8 }}>DNI</th>
              <th style={{ border: "1px solid #ccc", padding: 8 }}>Nombres</th>
              <th style={{ border: "1px solid #ccc", padding: 8 }}>Apellidos</th>
              <th style={{ border: "1px solid #ccc", padding: 8 }}>Fecha Nac.</th>
              <th style={{ border: "1px solid #ccc", padding: 8 }}>Género</th>
              <th style={{ border: "1px solid #ccc", padding: 8 }}>Ciudad</th>
              <th style={{ border: "1px solid #ccc", padding: 8 }}>Acciones</th>
            </tr>
          </thead>
          <tbody>
            {forms.map((f) => (
              <tr key={f._id}>
                <td style={{ border: "1px solid #ccc", padding: 8 }}>{f.dni}</td>
                <td style={{ border: "1px solid #ccc", padding: 8 }}>{f.nombres}</td>
                <td style={{ border: "1px solid #ccc", padding: 8 }}>{f.apellidos}</td>
                <td style={{ border: "1px solid #ccc", padding: 8 }}>{f.fechaNacimiento}</td>
                <td style={{ border: "1px solid #ccc", padding: 8 }}>{f.genero}</td>
                <td style={{ border: "1px solid #ccc", padding: 8 }}>{f.ciudad}</td>
                <td style={{ border: "1px solid #ccc", padding: 8 }}>
                  <button onClick={() => editForm(f)} style={{ marginRight: 6 }}>Editar</button>
                  <button onClick={() => deleteForm(f._id)}>Eliminar</button>
                </td>
              </tr>
            ))}
            {forms.length === 0 && (
              <tr>
                <td colSpan="7" style={{ textAlign: "center", padding: 12 }}>No hay registros</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default App;

// vue-form/src/App.vue
<template>
  <div class="app">
    <h1>Formulario Vue</h1>

    <form @submit.prevent="handleSubmit" class="formulario">
      <input type="text" v-model="formData.dni" placeholder="DNI" />
      <p v-if="errors.dni" class="error">{{ errors.dni }}</p>

      <input type="text" v-model="formData.nombres" placeholder="Nombres" />
      <p v-if="errors.nombres" class="error">{{ errors.nombres }}</p>

      <input type="text" v-model="formData.apellidos" placeholder="Apellidos" />
      <p v-if="errors.apellidos" class="error">{{ errors.apellidos }}</p>

      <input type="date" v-model="formData.fechaNacimiento" />
      <p v-if="errors.fechaNacimiento" class="error">{{ errors.fechaNacimiento }}</p>

      <div class="form-group">
        <label class="label-center">Género:</label>
        <div class="radio-group-horizontal">
          <label>
            <input type="radio" value="M" v-model="formData.genero" /> Masculino
          </label>
          <label>
            <input type="radio" value="F" v-model="formData.genero" /> Femenino
          </label>
        </div>
        <p v-if="errors.genero" class="error">{{ errors.genero }}</p>
      </div>

      <select v-model="formData.ciudad">
        <option value="">Seleccione ciudad</option>
        <option value="Quito">Quito</option>
        <option value="Guayaquil">Guayaquil</option>
        <option value="Milagro">Milagro</option>
      </select>
      <p v-if="errors.ciudad" class="error">{{ errors.ciudad }}</p>

      <button type="submit">{{ isEditing ? 'Actualizar' : 'Guardar' }}</button>
      <button type="button" v-if="isEditing" @click="cancelEdit">Cancelar</button>
    </form>

    <h2>Registros</h2>
    <table>
      <thead>
        <tr>
          <th>DNI</th>
          <th>Nombres</th>
          <th>Apellidos</th>
          <th>Fecha Nac.</th>
          <th>Género</th>
          <th>Ciudad</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="form in forms" :key="form._id">
          <td>{{ form.dni }}</td>
          <td>{{ form.nombres }}</td>
          <td>{{ form.apellidos }}</td>
          <td>{{ form.fechaNacimiento }}</td>
          <td>{{ form.genero }}</td>
          <td>{{ form.ciudad }}</td>
          <td>
            <button class="edit-btn" @click="editForm(form)">Editar</button>
            <button class="delete-btn" @click="deleteForm(form._id)">Eliminar</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      forms: [],
      formData: {
        dni: '',
        nombres: '',
        apellidos: '',
        fechaNacimiento: '',
        genero: '',
        ciudad: ''
      },
      errors: {},
      isEditing: false,
      editId: null
    };
  },
  methods: {
    async getForms() {
      const res = await fetch('http://localhost:5000/api/forms');
      this.forms = await res.json();
    },
    validateForm() {
      const errs = {};
      if (!this.formData.dni) errs.dni = 'DNI es obligatorio';
      if (!this.formData.nombres) errs.nombres = 'Nombres son obligatorios';
      if (!this.formData.apellidos) errs.apellidos = 'Apellidos son obligatorios';
      if (!this.formData.fechaNacimiento) errs.fechaNacimiento = 'Fecha de nacimiento es obligatoria';
      if (!this.formData.genero) errs.genero = 'Seleccione un género';
      if (!this.formData.ciudad) errs.ciudad = 'Seleccione una ciudad';
      return errs;
    },
    async handleSubmit() {
      this.errors = this.validateForm();
      if (Object.keys(this.errors).length) return;

      if (this.isEditing) {
        await fetch(`http://localhost:5000/api/form/${this.editId}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(this.formData)
        });
        this.isEditing = false;
        this.editId = null;
      } else {
        await fetch('http://localhost:5000/api/form', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(this.formData)
        });
      }

      this.formData = {
        dni: '',
        nombres: '',
        apellidos: '',
        fechaNacimiento: '',
        genero: '',
        ciudad: ''
      };
      this.getForms();
    },
    editForm(form) {
      this.isEditing = true;
      this.editId = form._id;
      this.formData = { ...form };
    },
    cancelEdit() {
      this.isEditing = false;
      this.editId = null;
      this.formData = {
        dni: '',
        nombres: '',
        apellidos: '',
        fechaNacimiento: '',
        genero: '',
        ciudad: ''
      };
    },
    async deleteForm(id) {
      await fetch(`http://localhost:5000/api/form/${id}`, { method: 'DELETE' });
      this.getForms();
    }
  },
  mounted() {
    this.getForms();
  }
};
</script>

<style>
/* Fondo general y centrado */
.app {
  max-width: 600px;
  margin: 20px auto;
  font-family: Arial, sans-serif;
  background-color: #fef6f0; /* pastel suave */
  padding: 20px;
  border-radius: 10px;
}

/* Títulos */
h1, h2 {
  text-align: center;
  color: #333;
}

/* Formulario */
.formulario {
  background: #fff0f5; /* pastel lila suave */
  padding: 15px;
  border-radius: 8px;
  margin-bottom: 20px;
  box-shadow: 0 0 5px rgba(0,0,0,0.05);
}

/* Inputs y select */
input, select, button {
  width: 100%;
  padding: 8px;
  margin: 6px 0;
  border-radius: 5px;
  border: 1px solid #ccc;
  box-sizing: border-box;
  background-color: #fffaf0; /* pastel claro */
  color: #333;
}

/* Botones */
button {
  cursor: pointer;
  background-color: #a8dadc; /* pastel azul */
  color: #333;
  border: none;
  font-weight: bold;
  margin-top: 5px;
}

button.edit-btn {
  background-color: #ffb6b9; /* pastel rosa */
  color: #333;
  border: none;
  padding: 5px 10px;
  border-radius: 4px;
  margin-right: 5px;
}

button.delete-btn {
  background-color: #f6c90e; /* pastel amarillo */
  color: #333;
  border: none;
  padding: 5px 10px;
  border-radius: 4px;
}

/* Radio buttons */
.radio-group-horizontal {
  display: flex;
  justify-content: center;
  gap: 15px;
  color: #333; /* color oscuro para que se note */
  font-weight: normal;
}
.label-center {
  display: block;
  text-align: center;
  font-weight: bold;
  margin-bottom: 5px;
  color: #333;
}

/* Errores */
.error {
  color: #e63946; /* rojo pastel */
  font-size: 0.85em;
  margin-top: 2px;
  margin-bottom: 5px;
}

/* Tabla */
table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 20px;
  background-color: #fffaf0;
}

th, td {
  padding: 8px;
  border: 1px solid #ccc;
  text-align: center;
  color: #333; /* color oscuro para todos los textos de la tabla */
}

th {
  background-color: #a8dadc;
  font-weight: bold;
}
</style>
